INPUT:
  MIN_SIZE_TRAIN: (512, )
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 1024  
MODEL:
  BACKBONE: "resnet50"
TRAIN:
  BATCH: 4
  LR: 0.01
  EPOCH: 24
  MILESTONES: [16, 20]
TEST:
  THRES: 0.05
  NMS_THRES: 0.6
  TOP_N: 1000
  POST_TOP_N: 100