INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333  
MODEL:
  BACKBONE: "resnet50"
TRAIN:
  BATCH: 8
  LR: 0.005
  EPOCH: 24
  MILESTONES: [16, 20]
TEST:
  PRE_THRES: 0.05
  NMS_THRES: 0.6
  TOP_N: 1000
  POST_TOP_N: 100