INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333  
MODEL:
  BACKBONE: "resnet50"
TRAIN:
  BATCH: 16
  LR: 0.01
  EPOCH: 12
  MILESTONES: [8, 10]
TEST:
  THRES: 0.05
  NMS_THRES: 0.6
  TOP_N: 1000
  POST_TOP_N: 100